### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by naturalc** [robregonm/yii2-pdf#12]
class MyController extends Controller {
        public function actionPdf(){
            Yii::$app->response->format = 'pdf';

            //Can you it if needed to rotate the page
            Yii::$container->set(Yii::$app->response->formatters['pdf']['class'], [
                'orientation' => 'Landscape', // This value will be ignored if format is a string value.
                'beforeRender' => function($mpdf, $data) {},
                ]);

            $this->layout = '//print';
            return $this->render('myview', []);
        }
    }

where odes $mpdf and $data come from?  is that line even something that we need?  the return from this is a pdf file?  what should 'myview' be, can it be a regular view that we can get a pdf from? or does it need to be special some how?

**Comment by robregonm** [comment]
1. `beforeRender` param is optional, however if you decide to use it, then the $mpdf and $data are arguments that are passed to the function. Btw, mPDF is the library used for converting HTML to PDF. If you don't need to this argument you can skip it.
2. Yes, when you execute the action you'll get a PDF file instead of HTML.
3. `'myview'` is a standard view which will be rendered as PDF (usually HTML, PHP, Smarty or Twig files)
4. This widget allows you to return PDF files using your standard PHP/HTML views. Maybe you'll need to do some extra fixes (due to PDF limitations or formatting).
