### ISSUE TITLE
How add new page with other page orientation?

### ISSUE THREAD

**Issue by githubjeka** [robregonm/yii2-pdf#14]
http://mpdf1.com/manual/index.php?tid=29
```php
$mpdf=new mPDF();
$mpdf->WriteHTML('Your Introduction');
$mpdf->AddPage('L','','','','',50,50,50,50,10,10);
$mpdf->WriteHTML('Your Book text');
```

I cant get $mpdf from your extension.

**Comment by robregonm** [comment]
Since this extension is based on mpdf, the all features relies on mpdf features, and it is focused on converting HTML response (usually views) to PDF format.
On this case, you should use `pagebreak` tag.
Take a look at: http://mpdf1.com/manual/index.php?tid=110

And your action in your controller should look like this (following the docs):

```php
public function actionPdf(){
        Yii::$app->response->format = 'pdf';

        Yii::$container->set(Yii::$app->response->formatters['pdf']['class'], [
            'beforeRender' => function($mpdf, $data) {},
            ]);

        $this->layout = '//print';
        return $this->render('myview', []);
    }
```

In `myview` file you should add the HTML that will be converted to HTML (and the `pagebreak` which is needed for changing the orientation on-the-fly)

**Comment by githubjeka** [comment]
How do orientation on-the-fly? Orientation will change for all pages via container. I tried.

**Comment by robregonm** [comment]
Please take a look at: http://mpdf1.com/manual/index.php?tid=110
That post indicates the way to change the orientation for the subsequent pages.

**Comment by githubjeka** [comment]
Thanks. I will try.

**Comment by githubjeka** [comment]
thnks again. It works.

**Comment by robregonm** [comment]
Cool. You're welcome
